name: Build and publish app

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'
      - '*.gradle'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: app
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 (corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: corretto
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Build with Gradle
        run: ./gradlew --no-daemon bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: '${{ secrets.KEYSTORE }}'
          alias: '${{ secrets.SIGNING_KEY_ALIAS }}'
          keyStorePassword: '${{ secrets.SIGNING_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.SIGNING_KEY_PASSWORD }}'

      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
          retention-days: 2

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download app bundle from artifact
        uses: actions/download-artifact@v4
        with:
          name: app-bundle
          path: ${{ github.workspace }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: aikain-mafioso
          workload_identity_provider: projects/184973361127/locations/global/workloadIdentityPools/github/providers/github
          service_account: github-actions@aikain-mafioso.iam.gserviceaccount.com

      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: app.mafioso
          releaseFiles: ${{ github.workspace }}/app-release.aab
          track: internal
